/*
 * FINBOURNE Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.517
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.scheduler.model;

import com.finbourne.scheduler.model.DaysOfWeek;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CombinedTrigger
 */
public class CombinedTriggerTest {
    private final CombinedTrigger model = new CombinedTrigger();

    /**
     * Model tests for CombinedTrigger
     */
    @Test
    public void testCombinedTrigger() {
        // TODO: test CombinedTrigger
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'file'
     */
    @Test
    public void fileTest() {
        // TODO: test file
    }

    /**
     * Test the property 'pollPeriod'
     */
    @Test
    public void pollPeriodTest() {
        // TODO: test pollPeriod
    }

    /**
     * Test the property 'bucket'
     */
    @Test
    public void bucketTest() {
        // TODO: test bucket
    }

    /**
     * Test the property 'triggerEveryFile'
     */
    @Test
    public void triggerEveryFileTest() {
        // TODO: test triggerEveryFile
    }

    /**
     * Test the property 'endOfTimeWindowOption'
     */
    @Test
    public void endOfTimeWindowOptionTest() {
        // TODO: test endOfTimeWindowOption
    }

    /**
     * Test the property 'daysAvailable'
     */
    @Test
    public void daysAvailableTest() {
        // TODO: test daysAvailable
    }

}
