/*
 * FINBOURNE Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.517
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.scheduler.model;

import com.finbourne.scheduler.model.ArgumentDefinition;
import com.finbourne.scheduler.model.RequiredResources;
import com.finbourne.scheduler.model.ResourceId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateJobRequest
 */
public class CreateJobRequestTest {
    private final CreateJobRequest model = new CreateJobRequest();

    /**
     * Model tests for CreateJobRequest
     */
    @Test
    public void testCreateJobRequest() {
        // TODO: test CreateJobRequest
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'imageName'
     */
    @Test
    public void imageNameTest() {
        // TODO: test imageName
    }

    /**
     * Test the property 'imageTag'
     */
    @Test
    public void imageTagTest() {
        // TODO: test imageTag
    }

    /**
     * Test the property 'command'
     */
    @Test
    public void commandTest() {
        // TODO: test command
    }

    /**
     * Test the property 'ttl'
     */
    @Test
    public void ttlTest() {
        // TODO: test ttl
    }

    /**
     * Test the property 'minCpu'
     */
    @Test
    public void minCpuTest() {
        // TODO: test minCpu
    }

    /**
     * Test the property 'maxCpu'
     */
    @Test
    public void maxCpuTest() {
        // TODO: test maxCpu
    }

    /**
     * Test the property 'minMemory'
     */
    @Test
    public void minMemoryTest() {
        // TODO: test minMemory
    }

    /**
     * Test the property 'maxMemory'
     */
    @Test
    public void maxMemoryTest() {
        // TODO: test maxMemory
    }

    /**
     * Test the property 'argumentDefinitions'
     */
    @Test
    public void argumentDefinitionsTest() {
        // TODO: test argumentDefinitions
    }

    /**
     * Test the property 'commandLineArgumentSeparator'
     */
    @Test
    public void commandLineArgumentSeparatorTest() {
        // TODO: test commandLineArgumentSeparator
    }

    /**
     * Test the property 'requiredResources'
     */
    @Test
    public void requiredResourcesTest() {
        // TODO: test requiredResources
    }

}
