/*
 * FINBOURNE Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.517
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.scheduler.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScanSummary
 */
public class ScanSummaryTest {
    private final ScanSummary model = new ScanSummary();

    /**
     * Model tests for ScanSummary
     */
    @Test
    public void testScanSummary() {
        // TODO: test ScanSummary
    }

    /**
     * Test the property 'fixable'
     */
    @Test
    public void fixableTest() {
        // TODO: test fixable
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'critical'
     */
    @Test
    public void criticalTest() {
        // TODO: test critical
    }

    /**
     * Test the property 'high'
     */
    @Test
    public void highTest() {
        // TODO: test high
    }

    /**
     * Test the property 'medium'
     */
    @Test
    public void mediumTest() {
        // TODO: test medium
    }

    /**
     * Test the property 'low'
     */
    @Test
    public void lowTest() {
        // TODO: test low
    }

    /**
     * Test the property 'negligible'
     */
    @Test
    public void negligibleTest() {
        // TODO: test negligible
    }

    /**
     * Test the property 'unknown'
     */
    @Test
    public void unknownTest() {
        // TODO: test unknown
    }

}
