/*
 * FINBOURNE Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.517
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.scheduler.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Tag
 */
public class TagTest {
    private final Tag model = new Tag();

    /**
     * Model tests for Tag
     */
    @Test
    public void testTag() {
        // TODO: test Tag
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'pullTime'
     */
    @Test
    public void pullTimeTest() {
        // TODO: test pullTime
    }

    /**
     * Test the property 'pushTime'
     */
    @Test
    public void pushTimeTest() {
        // TODO: test pushTime
    }

    /**
     * Test the property 'signed'
     */
    @Test
    public void signedTest() {
        // TODO: test signed
    }

    /**
     * Test the property 'immutable'
     */
    @Test
    public void immutableTest() {
        // TODO: test immutable
    }

}
