/*
 * FINBOURNE Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.517
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.scheduler.model;

import com.finbourne.scheduler.model.BucketWatcherTrigger;
import com.finbourne.scheduler.model.CombinedTrigger;
import com.finbourne.scheduler.model.TimeTrigger;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Trigger
 */
public class TriggerTest {
    private final Trigger model = new Trigger();

    /**
     * Model tests for Trigger
     */
    @Test
    public void testTrigger() {
        // TODO: test Trigger
    }

    /**
     * Test the property 'bucketWatcherTrigger'
     */
    @Test
    public void bucketWatcherTriggerTest() {
        // TODO: test bucketWatcherTrigger
    }

    /**
     * Test the property 'timeTrigger'
     */
    @Test
    public void timeTriggerTest() {
        // TODO: test timeTrigger
    }

    /**
     * Test the property 'combinedTrigger'
     */
    @Test
    public void combinedTriggerTest() {
        // TODO: test combinedTrigger
    }

}
