/*
 * FINBOURNE Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.517
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.scheduler.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UploadImageRequest
 */
public class UploadImageRequestTest {
    private final UploadImageRequest model = new UploadImageRequest();

    /**
     * Model tests for UploadImageRequest
     */
    @Test
    public void testUploadImageRequest() {
        // TODO: test UploadImageRequest
    }

    /**
     * Test the property 'imageName'
     */
    @Test
    public void imageNameTest() {
        // TODO: test imageName
    }

}
