/*
 * FINBOURNE Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.517
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.scheduler.api;

import com.finbourne.scheduler.ApiException;
import com.finbourne.scheduler.model.CreateJobRequest;
import com.finbourne.scheduler.model.JobDefinition;
import com.finbourne.scheduler.model.JobRunResult;
import com.finbourne.scheduler.model.LusidProblemDetails;
import com.finbourne.scheduler.model.LusidValidationProblemDetails;
import com.finbourne.scheduler.model.ResourceListOfJobDefinition;
import com.finbourne.scheduler.model.ResourceListOfJobHistory;
import com.finbourne.scheduler.model.ResourceListOfScheduleDefinition;
import com.finbourne.scheduler.model.StartJobRequest;
import com.finbourne.scheduler.model.StartJobResponse;
import com.finbourne.scheduler.model.UpdateJobRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JobsApi
 */
@Ignore
public class JobsApiTest {

    private final JobsApi api = new JobsApi();

    
    /**
     * [EXPERIMENTAL] CreateJob: Create a new job
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createJobTest() throws ApiException {
        CreateJobRequest createJobRequest = null;
        JobDefinition response = api.createJob(createJobRequest);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] DeleteJob: Delete a job
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteJobTest() throws ApiException {
        String scope = null;
        String code = null;
        ResourceListOfScheduleDefinition response = api.deleteJob(scope, code);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] GetHistory: Get the history of job runs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoryTest() throws ApiException {
        String page = null;
        List<String> sortBy = null;
        Integer start = null;
        Integer limit = null;
        String filter = null;
        ResourceListOfJobHistory response = api.getHistory(page, sortBy, start, limit, filter);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] GetJobConsoleOutput: Gets the console output of a specific job run
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJobConsoleOutputTest() throws ApiException {
        String runId = null;
        String response = api.getJobConsoleOutput(runId);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] GetRunHistory: Get the history for a single job run
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRunHistoryTest() throws ApiException {
        String runId = null;
        JobRunResult response = api.getRunHistory(runId);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] GetSchedulesForAJob: Get all the schedules for a single job
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchedulesForAJobTest() throws ApiException {
        String scope = null;
        String code = null;
        ResourceListOfScheduleDefinition response = api.getSchedulesForAJob(scope, code);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] ListJobs: List the available jobs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listJobsTest() throws ApiException {
        String page = null;
        List<String> sortBy = null;
        Integer start = null;
        Integer limit = null;
        String filter = null;
        ResourceListOfJobDefinition response = api.listJobs(page, sortBy, start, limit, filter);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] RunJob: Run a job immediately
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runJobTest() throws ApiException {
        String scope = null;
        String code = null;
        StartJobRequest startJobRequest = null;
        StartJobResponse response = api.runJob(scope, code, startJobRequest);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] UpdateJob: Update a JobDefinition
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateJobTest() throws ApiException {
        String scope = null;
        String code = null;
        UpdateJobRequest updateJobRequest = null;
        JobDefinition response = api.updateJob(scope, code, updateJobRequest);

        // TODO: test validations
    }
    
}
