/*
 * FINBOURNE Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.517
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.scheduler.api;

import com.finbourne.scheduler.ApiException;
import com.finbourne.scheduler.model.CreateScheduleRequest;
import com.finbourne.scheduler.model.LusidProblemDetails;
import com.finbourne.scheduler.model.LusidValidationProblemDetails;
import com.finbourne.scheduler.model.ResourceListOfScheduleDefinition;
import com.finbourne.scheduler.model.ScheduleDefinition;
import com.finbourne.scheduler.model.StartScheduleResponse;
import com.finbourne.scheduler.model.UpdateScheduleRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchedulesApi
 */
@Ignore
public class SchedulesApiTest {

    private final SchedulesApi api = new SchedulesApi();

    
    /**
     * [EXPERIMENTAL] CreateSchedule: Create a Schedule for a job
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createScheduleTest() throws ApiException {
        CreateScheduleRequest createScheduleRequest = null;
        ScheduleDefinition response = api.createSchedule(createScheduleRequest);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] DeleteSchedule: Delete a schedule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteScheduleTest() throws ApiException {
        String scope = null;
        String code = null;
        api.deleteSchedule(scope, code);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] EnabledSchedule: Enable/disable a schedule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enabledScheduleTest() throws ApiException {
        String scope = null;
        String code = null;
        Boolean enable = null;
        ScheduleDefinition response = api.enabledSchedule(scope, code, enable);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] GetSchedule: Get a single Schedule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getScheduleTest() throws ApiException {
        String scope = null;
        String code = null;
        ScheduleDefinition response = api.getSchedule(scope, code);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] ListSchedules: List the available Schedules
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSchedulesTest() throws ApiException {
        String page = null;
        List<String> sortBy = null;
        Integer start = null;
        Integer limit = null;
        String filter = null;
        ResourceListOfScheduleDefinition response = api.listSchedules(page, sortBy, start, limit, filter);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] RunSchedule: Run a schedule immediately
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runScheduleTest() throws ApiException {
        String scope = null;
        String code = null;
        StartScheduleResponse response = api.runSchedule(scope, code);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] UpdateSchedule: Update a schedule.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateScheduleTest() throws ApiException {
        String scope = null;
        String code = null;
        UpdateScheduleRequest updateScheduleRequest = null;
        ScheduleDefinition response = api.updateSchedule(scope, code, updateScheduleRequest);

        // TODO: test validations
    }
    
}
